### ISSUE TITLE
the tiles repository does not work.

### ISSUE THREAD

**Issue by hjonescool2023** [FranklinDM/AvalonBar#14]
every time i try to go download tiles onedrive keeps telling me that there was an error. idk what happened but i JUST WANNA DOWNLOAD LONGBAR TILES!!!

**Comment by fofajardo** [comment]
This isn't the issue tracker for LongBar. We no longer make use of those direct OneDrive links anymore in the Tiles Library.

However, we've archived the original LongBar tiles and they're available in a [separate](https://github.com/AvalonBar/tiles-provider-longbar) repository.
